# Site settings
title: shixin
SEOTitle: shixin的博客 | Xinshix Blog
header-img: img/home-bg.jpg
email: 1264110731@qq.com
description: "这里是 xinshix 的个人博客，与你一起发现更大的世界 | 要做一个有 swag 的程序员"
keyword: "shixin, xinshix, 博客, 个人网站, 通信工程, 嵌入式, 大数据, 人工智能, C++, STM32"
url: "https://xinshix09.dpdns.org" # 你的域名
baseurl: "" # 如果是子路径部署就写，比如 '/blog'

future: true

# SNS settings（如有账号可以填）
weibo_username: 
zhihu_username: 
github_username: xinshix09
twitter_username: 
# facebook_username: 
# linkedin_username: 

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true
# timezone: CN

# Plugins
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# 评论设置（Disqus可选）
disqus_username: 

# 网易云跟帖（一般不再使用）
netease_comment: false

# Google Analytics（如不使用可删除）
ga_track_id: ""
ga_domain: xinshix09.dpdns.org

# Sidebar settings
sidebar: true
sidebar-about-description: "通信工程 / 嵌入式开发 / 大数据分析 / 要做一个有 swag 的程序员"
sidebar-avatar: https://avatars.githubusercontent.com/u/your_github_id.png # 建议上传头像或使用 GitHub 头像

# 标签
featured-tags: true
featured-condition-size: 1

# PWA
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax（数学公式支持）
page-mathjax: false

# 友链（可选）
friends:
  [
    { title: "安徽工程大学", href: "https://www.ahpu.edu.cn/" },
    { title: "皖江工学院", href: "https://www.wjut.edu.cn/" }
  ]
